version: '3'
services:
  dev:
    build: .
    volumes:
      - ./:/code
      - ./data:/data
    environment:
      - CLIENT_ID
      - CLIENT_SECRET
      - API_DATA
      - CUSTOMER_ID
      - CUSTOMER_ID_WITH_DASH
      - DEVELOPER_TOKEN
